import fs from "fs-extra";
import path from "path";
import { setup } from "@/lib/project-setup";

export const BANNER_COMMENT = `
/**
 * This file was automatically generated by json-schema-to-typescript && mdx-forge.
 * 
 * DO NOT MODIFY IT BY HAND.
 * Instead run npx mdx-forge forge to regenerate this file.
 * 
 * To modify your types, adjust your mdx.config.ts
 * 
 */`;

export async function writeUtilsTemplate(utilsDirPath: string, outputDirPath: string) {
  const UTILS_TEMPLATE = `
import {promises as fs} from "fs"
import path from "path"
// hint: run "npx mdx-forge forge" to generate types and fix error
import { MdxFileInterface } from "${outputDirPath}/${setup.typesDirName}/${setup.tsFileName.split(".")[0]}"

const DIR_PATH = "${outputDirPath}/${setup.contentDirName}"
const ALLOWED_EXTENSION = ".json"

export async function getMdxFiles (): Promise<MdxFileInterface[]>  {
    try {
        const cwd = process.cwd()
        const paths = (await fs.readdir(path.join(cwd, DIR_PATH))).filter(file => path.extname(file) === ALLOWED_EXTENSION)
        const jsons = []
        
        for (const p of paths) {
            const file = await fs.readFile(path.join(cwd, DIR_PATH, p), "utf-8")
            jsons.push(JSON.parse(file))
        }

        return jsons
    }
    catch(e) {
        throw e
    }
}
    `;

  try {
    await fs.outputFile(path.resolve(utilsDirPath, setup.utilsFileName), UTILS_TEMPLATE, "utf-8");
  } catch (e) {
    throw new Error("Something went wrong when utils template file.");
  }
}

const MDX_EXAMPLE = `---
title: "Example file"
tags:
- hello
- world
category: articles
---

## Vision

Throughout my career, coding has not just been a day job but also a passion that keeps me engaged late into the night. It is during these hours that some of my most creative ideas emerge—ideas that I am eager to experiment with and develop further.

This platform is my way of **sharing those bursts of creativity with you**. 

Whether you're here to find inspiration or to learn something new, I hope these documents serve as a valuable resource. 

**Feel free to pick anything** that catches your eye and use it however you see fit.
`;

export async function writeMdxExample(absoluteContentDirPath: string): Promise<void> {
  try {
    await fs.outputFile(path.join(absoluteContentDirPath, setup.exampleFileName), MDX_EXAMPLE, "utf-8");
  } catch (e) {
    throw new Error("Something went wrong when creating example file.");
  }
}
