import {z} from "zod";

const ENGINE_CONFIG_DIFFICULTIES = {
  EASY: "EASY",
  HARD: "HARD",
  ANALYZE: "ANALYZE",
} as const;

const ENGINE_DIFFICULTY_ARRAY = [
  ENGINE_CONFIG_DIFFICULTIES.EASY,
  ENGINE_CONFIG_DIFFICULTIES.HARD,
  ENGINE_CONFIG_DIFFICULTIES.ANALYZE,
] as const;

const ENGINE_DIFFICULTY_SCHEMA = z.enum(ENGINE_DIFFICULTY_ARRAY);

type EngineDifficultyKeys =
  (typeof ENGINE_CONFIG_DIFFICULTIES)[keyof typeof ENGINE_CONFIG_DIFFICULTIES];

export {
  ENGINE_CONFIG_DIFFICULTIES,
  ENGINE_DIFFICULTY_ARRAY,
  ENGINE_DIFFICULTY_SCHEMA,
  type EngineDifficultyKeys,
};
